# Generated by Django 2.2.3 on 2019-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('first_class_normal_price', models.FloatField()),
                ('first_class_spot_price', models.FloatField()),
                ('second_class_normal_price', models.FloatField()),
                ('second_class_spot_price', models.FloatField()),
            ],
        ),
    ]
