# Generated by Django 2.2.3 on 2019-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='capacity_first_class',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='capacity_second_class',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
